version: '3.8'

services:
  web:
    build: ./docker/web
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cde3bgt5_root
      MYSQL_USER: ncwww
      MYSQL_PASSWORD: cde3bgt5
      MYSQL_DATABASE: message_board

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"  
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: cde3bgt5_root
    depends_on:
      - mysql

volumes:
  mysql-data:
